In [1]:
import pandas as pd
from pathlib import Path

In [2]:
file_path = Path('./data/healthcare_dataset.csv')

In [3]:
healthcare_df = pd.read_csv(file_path)

In [4]:
healthcare_df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [5]:
healthcare_df.tail()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [6]:
healthcare_df.columns

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='object')

In [7]:
healthcare_df.dtypes

Name                   object
Age                     int64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number             int64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

In [8]:
healthcare_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [9]:
healthcare_df.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

In [11]:
#convert date columns
healthcare_df['Date of Admission'] = pd.to_datetime(healthcare_df['Date of Admission'])
healthcare_df['Discharge Date'] = pd.to_datetime(healthcare_df['Discharge Date'])

In [12]:
healthcare_df.describe()

,Age,Date of Admission,Billing Amount,Room Number,Discharge Date
count,55500.000000,55500,55500.000000,55500.000000,55500
mean,51.539459,2021-11-01 01:02:22.443243008,25539.316097,301.134829,2021-11-16 13:15:20.821621504
min,13.000000,2019-05-08 00:00:00,-2008.492140,101.000000,2019-05-09 00:00:00
25%,35.000000,2020-07-28 00:00:00,13241.224652,202.000000,2020-08-12 00:00:00
50%,52.000000,2021-11-01 00:00:00,25538.069376,302.000000,2021-11-17 00:00:00
75%,68.000000,2023-02-03 00:00:00,37820.508436,401.000000,2023-02-18 00:00:00
max,89.000000,2024-05-07 00:00:00,52764.276736,500.000000,2024-06-06 00:00:00
std,19.602454,NaN,14211.454431,115.243069,NaN

In [15]:
#create new feature
healthcare_df['Length of Stay'] = (healthcare_df['Discharge Date'] - healthcare_df['Date of Admission']).dt.days

In [16]:
from autoviz.AutoViz_Class import AutoViz_Class
AV = AutoViz_Class()

In [17]:
df_report = AV.AutoViz(filename="", dfte=healthcare_df)

Shape of your Data Set loaded: (55500, 16)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  1
    Number of Integer-Categorical Columns =  3
    Number of String-Categorical Columns =  7
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  1
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  2
    Number of Date Time Columns =  2
    Number of ID Columns =  0
    Number of Columns to Delete =  0
    16 Predictors classified...
        No variables removed since no ID or low-information variables found in data set
To fix these data quality issues in the dataset, import FixDQ from autoviz...
There are 534 duplicate rows in your dataset
    Alert: Dropping duplicate rows can sometimes cause your column data types to change to object!
    All variables classified into correct types.

[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package names to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package shakespeare to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package stopwords to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package treebank to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package omw to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package wordnet to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package punkt to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\MorganHouston\AppData\Roaming\nltk_data.
[nltk_data]    |     ..
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection popular

All Plots done
Time to run AutoViz = 35 seconds

 ###################### AUTO VISUALIZATION Completed ########################

In [18]:
healthcare_df[healthcare_df.duplicated()]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
50023,Samuel joYCe,56,Male,O+,Arthritis,2022-11-03,Krista Hartman,Thomas-Ballard,UnitedHealthcare,15654.830587,157,Urgent,2022-11-22,Aspirin,Inconclusive,19
50040,KIMBErly vasqueZ,26,Male,A-,Obesity,2023-10-23,Jennifer Bennett,Cowan Inc,UnitedHealthcare,38142.109678,313,Urgent,2023-11-18,Penicillin,Abnormal,26
50055,SCoTT tHOrNton,55,Female,B-,Obesity,2021-04-08,Joshua Ingram,Keller LLC,Medicare,30894.904511,455,Urgent,2021-04-15,Aspirin,Abnormal,7
50070,wiLliam LEe,27,Female,O+,Arthritis,2020-01-31,Lauren Montgomery,Winters-Simon,Cigna,46229.434901,153,Elective,2020-02-13,Lipitor,Normal,13
50078,chRistOPheR NoRrIs,38,Male,AB-,Arthritis,2023-01-14,Denise Blair,Inc Morales,Medicare,9072.127142,452,Emergency,2023-02-12,Penicillin,Normal,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55461,connOR coMPTon,63,Male,A+,Asthma,2021-08-21,Jonathan Allen,"and Willis Mullins, Bowers",Medicare,1936.702824,375,Emergency,2021-09-16,Paracetamol,Normal,26
55462,alYSsA mIlLER,35,Female,A-,Diabetes,2022-06-30,Ryan Price,Shelton-Gallagher,UnitedHealthcare,2210.460898,289,Elective,2022-07-27,Penicillin,Normal,27
55464,ChRIs huGHeS,35,Female,AB-,Obesity,2024-02-28,Katelyn Perry,Lyons-Hansen,Blue Cross,11889.154513,128,Emergency,2024-03-14,Paracetamol,Abnormal,15
55484,keNNEtH alvarez,80,Male,O+,Cancer,2022-05-05,Andrew Conner,Sons Mayo and,Cigna,45653.802310,114,Elective,2022-05-17,Aspirin,Normal,12
55491,lInDA grIFfin,47,Female,O+,Obesity,2020-06-21,Danielle Davis,"and King Jordan Johnson,",Aetna,15715.551079,310,Emergency,2020-06-25,Lipitor,Abnormal,4

In [20]:
# Filter all duplicate rows (including the first occurrence)
all_duplicates = healthcare_df[healthcare_df.duplicated(keep=False)]

# Display only duplicates
all_duplicates

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
64,Nancy glOVeR,58,Male,A-,Hypertension,2020-05-08,Jennifer Larson,"Khan, and Rodriguez Fischer",Medicare,19183.168885,378,Emergency,2020-06-01,Aspirin,Abnormal,24
107,DAVid higgInS,49,Female,B-,Arthritis,2021-03-05,Erin Henderson MD,"Evans and Hall Schneider,",Medicare,24948.477824,361,Emergency,2021-03-20,Penicillin,Abnormal,15
148,RoBErt hIGGInS,42,Male,AB-,Asthma,2021-05-06,Scott Davis,"and Ford Lee, Rodriguez",Medicare,13355.782085,451,Elective,2021-05-29,Ibuprofen,Inconclusive,23
154,kevIn HiCKs,66,Male,AB+,Arthritis,2021-06-23,Kelly Murphy,Robinson Inc,Medicare,1897.891727,196,Elective,2021-07-09,Ibuprofen,Abnormal,16
159,miCHAeL TayloR,29,Male,O-,Asthma,2020-02-27,Erica Mccormick,Donaldson-Frey,Medicare,41939.119937,453,Elective,2020-03-26,Ibuprofen,Normal,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55461,connOR coMPTon,63,Male,A+,Asthma,2021-08-21,Jonathan Allen,"and Willis Mullins, Bowers",Medicare,1936.702824,375,Emergency,2021-09-16,Paracetamol,Normal,26
55462,alYSsA mIlLER,35,Female,A-,Diabetes,2022-06-30,Ryan Price,Shelton-Gallagher,UnitedHealthcare,2210.460898,289,Elective,2022-07-27,Penicillin,Normal,27
55464,ChRIs huGHeS,35,Female,AB-,Obesity,2024-02-28,Katelyn Perry,Lyons-Hansen,Blue Cross,11889.154513,128,Emergency,2024-03-14,Paracetamol,Abnormal,15
55484,keNNEtH alvarez,80,Male,O+,Cancer,2022-05-05,Andrew Conner,Sons Mayo and,Cigna,45653.802310,114,Elective,2022-05-17,Aspirin,Normal,12
55491,lInDA grIFfin,47,Female,O+,Obesity,2020-06-21,Danielle Davis,"and King Jordan Johnson,",Aetna,15715.551079,310,Emergency,2020-06-25,Lipitor,Abnormal,4

In [22]:
# Filter all_duplicates for a specific value in a column
filtered_duplicates = all_duplicates[all_duplicates['Age'] == 58]

# Display the filtered rows
filtered_duplicates

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
64,Nancy glOVeR,58,Male,A-,Hypertension,2020-05-08,Jennifer Larson,"Khan, and Rodriguez Fischer",Medicare,19183.168885,378,Emergency,2020-06-01,Aspirin,Abnormal,24
5001,kATHLEeN davID,58,Female,AB+,Obesity,2020-06-03,Tracy Flores,Choi-Brown,UnitedHealthcare,15304.848440,140,Emergency,2020-06-24,Lipitor,Inconclusive,21
6954,mARISsa miLES,58,Female,O-,Arthritis,2023-10-10,Brandi Lozano,"Dillon Nichols, Kane and",UnitedHealthcare,15300.911357,461,Urgent,2023-11-06,Ibuprofen,Normal,27
15699,kENNETH ChapMaN,58,Male,AB+,Arthritis,2023-07-12,Emily Stewart,PLC Hodges,Medicare,16082.281042,353,Urgent,2023-07-31,Lipitor,Abnormal,19
16156,JOhN fERRELl,58,Female,O-,Hypertension,2019-05-20,Randy Calderon,Inc Spencer,Medicare,-308.584269,394,Emergency,2019-05-27,Paracetamol,Inconclusive,7
19295,TARA puGH,58,Male,B-,Diabetes,2019-09-21,Amanda Price,"Marshall Soto Sanchez, and",Medicare,15910.705368,458,Urgent,2019-10-09,Penicillin,Abnormal,18
19821,AllisOn cocHRan,58,Female,B+,Hypertension,2022-05-03,Kevin Owens,Jackson-Hernandez,Cigna,28575.321906,234,Urgent,2022-05-28,Aspirin,Inconclusive,25
21927,Dr. RacHAel maRTIn,58,Male,A-,Obesity,2024-02-10,Marcus Clarke,"Baker Mills and Cobb,",Blue Cross,20945.051697,376,Elective,2024-03-09,Lipitor,Inconclusive,28
30464,SteveN YouNG,58,Female,O-,Obesity,2022-08-24,Troy York,"and Miller Gill Davenport,",Cigna,25995.907318,385,Urgent,2022-09-09,Penicillin,Inconclusive,16
32934,aNdrEw HANsen,58,Female,O+,Asthma,2019-11-04,Jeffrey Wilson,"Christensen and Duffy Leblanc,",Aetna,29909.823121,488,Urgent,2019-11-18,Ibuprofen,Inconclusive,14
35426,JeSSiCA mcguIRe,58,Female,A-,Cancer,2023-05-12,Michael Carrillo,Lamb-Henry,Aetna,19913.653075,202,Elective,2023-05-24,Aspirin,Abnormal,12
37821,bARRy HUGhEs,58,Male,AB-,Obesity,2024-05-02,Margaret Cox,Cole-Vargas,Aetna,32739.039718,129,Urgent,2024-05-31,Ibuprofen,Inconclusive,29
46779,kELly bArReTt,58,Male,A-,Cancer,2021-01-29,Gary Phillips,Garrett-Hernandez,Blue Cross,46101.574303,480,Emergency,2021-02-09,Penicillin,Abnormal,11
50159,mARISsa miLES,58,Female,O-,Arthritis,2023-10-10,Brandi Lozano,"Dillon Nichols, Kane and",UnitedHealthcare,15300.911357,461,Urgent,2023-11-06,Ibuprofen,Normal,27
50596,JeSSiCA mcguIRe,58,Female,A-,Cancer,2023-05-12,Michael Carrillo,Lamb-Henry,Aetna,19913.653075,202,Elective,2023-05-24,Aspirin,Abnormal,12
51347,bARRy HUGhEs,58,Male,AB-,Obesity,2024-05-02,Margaret Cox,Cole-Vargas,Aetna,32739.039718,129,Urgent,2024-05-31,Ibuprofen,Inconclusive,29
51498,aNdrEw HANsen,58,Female,O+,Asthma,2019-11-04,Jeffrey Wilson,"Christensen and Duffy Leblanc,",Aetna,29909.823121,488,Urgent,2019-11-18,Ibuprofen,Inconclusive,14
52765,SteveN YouNG,58,Female,O-,Obesity,2022-08-24,Troy York,"and Miller Gill Davenport,",Cigna,25995.907318,385,Urgent,2022-09-09,Penicillin,Inconclusive,16
53180,Dr. RacHAel maRTIn,58,Male,A-,Obesity,2024-02-10,Marcus Clarke,"Baker Mills and Cobb,",Blue Cross,20945.051697,376,Elective,2024-03-09,Lipitor,Inconclusive,28
53509,kELly bArReTt,58,Male,A-,Cancer,2021-01-29,Gary Phillips,Garrett-Hernandez,Blue Cross,46101.574303,480,Emergency,2021-02-09,Penicillin,Abnormal,11
53880,kENNETH ChapMaN,58,Male,AB+,Arthritis,2023-07-12,Emily Stewart,PLC Hodges,Medicare,16082.281042,353,Urgent,2023-07-31,Lipitor,Abnormal,19
54280,AllisOn cocHRan,58,Female,B+,Hypertension,2022-05-03,Kevin Owens,Jackson-Hernandez,Cigna,28575.321906,234,Urgent,2022-05-28,Aspirin,Inconclusive,25
54738,TARA puGH,58,Male,B-,Diabetes,2019-09-21,Amanda Price,"Marshall Soto Sanchez, and",Medicare,15910.705368,458,Urgent,2019-10-09,Penicillin,Abnormal,18
54972,Nancy glOVeR,58,Male,A-,Hypertension,2020-05-08,Jennifer Larson,"Khan, and Rodriguez Fischer",Medicare,19183.168885,378,Emergency,2020-06-01,Aspirin,Abnormal,24
55276,JOhN fERRELl,58,Female,O-,Hypertension,2019-05-20,Randy Calderon,Inc Spencer,Medicare,-308.584269,394,Emergency,2019-05-27,Paracetamol,Inconclusive,7
55368,kATHLEeN davID,58,Female,AB+,Obesity,2020-06-03,Tracy Flores,Choi-Brown,UnitedHealthcare,15304.848440,140,Emergency,2020-06-24,Lipitor,Inconclusive,21

In [27]:
healthcare_df.shape

(55500, 16)

In [25]:
#drop duplicates
dedup_healthcare = healthcare_df.drop_duplicates()

In [28]:
dedup_healthcare.shape

(54966, 16)