In [1]:
import pandas as pd
from pathlib import Path

In [2]:
data_path = Path('./data/healthcare_dataset.csv')

In [3]:
healthcare_df = pd.read_csv(data_path)

In [4]:
healthcare_df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [5]:
healthcare_df['Date of Admission'] = pd.to_datetime(healthcare_df['Date of Admission'])
healthcare_df['Discharge Date'] = pd.to_datetime(healthcare_df['Discharge Date'])

#create new feature
healthcare_df['Length of Stay'] = (healthcare_df['Discharge Date'] - healthcare_df['Date of Admission']).dt.days

In [6]:
healthcare_df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20

In [7]:
#drop duplicates
dedup_healthcare = healthcare_df.drop_duplicates()

In [13]:
dedup_healthcare.nunique()

Name                  49992
Age                      77
Gender                    2
Blood Type                8
Medical Condition         6
Date of Admission      1827
Doctor                40341
Hospital              39876
Insurance Provider        5
Billing Amount        50000
Room Number             400
Admission Type            3
Discharge Date         1856
Medication                5
Test Results              3
Length of Stay           30
dtype: int64

In [8]:
#TODO later - look at exploring predicivitivesness of features (ex: is insurance provider more important than doctor/hospital - how does this line up with tanya's experience)

In [14]:
healthcare_encoded = pd.get_dummies(dedup_healthcare, columns=['Gender', 'Blood Type', 'Medical Condition','Insurance Provider','Admission Type','Medication','Test Results'], dtype=int)

In [15]:
healthcare_encoded.head()

,Name,Age,Date of Admission,Doctor,Hospital,Billing Amount,Room Number,Discharge Date,Length of Stay,Gender_Female,...,Admission Type_Emergency,Admission Type_Urgent,Medication_Aspirin,Medication_Ibuprofen,Medication_Lipitor,Medication_Paracetamol,Medication_Penicillin,Test Results_Abnormal,Test Results_Inconclusive,Test Results_Normal
0,Bobby JacksOn,30,2024-01-31,Matthew Smith,Sons and Miller,18856.281306,328,2024-02-02,2,0,...,0,1,0,0,0,1,0,0,0,1
1,LesLie TErRy,62,2019-08-20,Samantha Davies,Kim Inc,33643.327287,265,2019-08-26,6,0,...,1,0,0,1,0,0,0,0,1,0
2,DaNnY sMitH,76,2022-09-22,Tiffany Mitchell,Cook PLC,27955.096079,205,2022-10-07,15,1,...,1,0,1,0,0,0,0,0,0,1
3,andrEw waTtS,28,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",37909.782410,450,2020-12-18,30,1,...,0,0,0,1,0,0,0,1,0,0
4,adrIENNE bEll,43,2022-09-19,Kathleen Hanna,White-White,14238.317814,458,2022-10-09,20,1,...,0,1,0,0,0,0,1,1,0,0